### PR TITLE
support smart-leds-trait 0.2 and 0.3

### PR DESCRIPTION
**Pull request by chinoto**
#30 and #34 have been in limbo due to incompatibility with 0.2. @jannic wrote code to add compatibility to #30, but the author of #30 hasn't accepted it yet. As odd as it is, I hope it is acceptable to submit their work for them.

### CODE REVIEW

**Comment by 9names** [comment]
Have you tested it with both versions of the trait to confirm it works?
Got any tests/examples you can share?

**Comment by chinoto** [comment]
I had not... Looks like it works with either version. Do you want the example included in this repo? https://github.com/chinoto/ws2812-pio-rs/commit/8e73f8293d8d972a63022c495ff19aa607801903

**Comment by chinoto** [comment]
Do you need something else?

**Review by 9names — APPROVED** [review]
Don't need anything else, thanks for linking to an example - made it quick to test.
Please make a PR for your example code once this is merged. I personally always want examples for lib crates but we'll let everyone else weigh in too.

Thanks for your patience, it's a busy time of year.

**Pull request merged**
